### ISSUE TITLE
Progress reports are output to console

### ISSUE THREAD

**Issue by aweiker** [jlouis/fuse#19]
I am evaluating fuse right now and when I added `fuse` to the list of applications I am getting progress reports output every time that a process starts. The main issue with this is that it is causing lots of noise in my unit .

Is there a way to suppress and or customize this output?

**Comment by jlouis** [comment]
Yes, it is all in how you configure the SASL application and if it should have a `tty_error_logger`. The reason we need SASL in fuse is because the (global) `alarm_handler` lives inside SASL and is use to raise and clear alarms when fuses go bad or when they heals again.

https://github.com/jlouis/fuse/blob/master/test/fuse_eqc.erl#L648-L655 can be a start for what to tweak. Another option is simply to pick up `lager` and use it instead, overriding all the standard SASL stuff. This is what I do in most production systems.

**Comment by aweiker** [comment]
Thank you for the details. I'm using Elixir and it is as simple as adding this to my `config/test.exs` to turn it off.

```Elixir
config :fuse, monitor: false
config :sasl, sasl_error_logger: false, errlog_type: :error
```
